'use client';
import React,{useState} from 'react';
import {api,errMsg} from './lib';
export * from './lib';
export function Login({login,request}:{login:(phone:string,code:string)=>Promise<void>;request:(phone:string)=>Promise<string|undefined>}){const[phone,setPhone]=useState('');const[code,setCode]=useState('');const[dev,setDev]=useState('');const[err,setErr]=useState('');const[step,setStep]=useState(0);return <div className="login"><div className="card"><h1>مشاوير</h1><p className="muted">لوحة الإدارة والتشغيل</p>{step===0?<><label>رقم الموبايل المصري</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="01XXXXXXXXX"/><button className="btn" style={{width:'100%',marginTop:10}} onClick={async()=>{try{setDev(await request(phone)||'');setStep(1)}catch(e){setErr(errMsg(e))}}}>إرسال الكود</button></>:<><label>كود الدخول</label><input className="input" value={code} onChange={e=>setCode(e.target.value)}/><p className="muted">{dev?`كود التطوير: ${dev}`:''}</p><button className="btn" style={{width:'100%',marginTop:10}} onClick={async()=>{try{await login(phone,code)}catch(e){setErr(errMsg(e))}}}>دخول</button></>}{err&&<div className="error" style={{marginTop:10}}>{err}</div>}</div></div>}
export interface Staff{id:string;name?:string|null;phone:string;roles:string[];perms:string[];businesses:any[]}
export interface ApiError extends Error{code?:string;status?:number}
export const API_URL=(process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000').replace(/\/$/,'');
export const tokens={access:null as string|null,refresh:null as string|null,async load(){this.access=localStorage.getItem('msh.d.a');this.refresh=localStorage.getItem('msh.d.r');return!!this.refresh},async set(a:string,r:string){this.access=a;this.refresh=r;localStorage.setItem('msh.d.a',a);localStorage.setItem('msh.d.r',r)},async clear(){this.access=null;this.refresh=null;localStorage.removeItem('msh.d.a');localStorage.removeItem('msh.d.r')}};
export async function api<T=any>(path:string,o:{method?:string;body?:any;query?:Record<string,unknown>}={}){const q=o.query?'?'+Object.entries(o.query).filter(([,v])=>v!=null&&v!=='').map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join('&'):'';let r=await fetch(API_URL+path+q,{method:o.method|| (o.body!==undefined?'POST':'GET'),headers:{'content-type':'application/json',...(tokens.access?{authorization:`Bearer ${tokens.access}`}:{})},body:o.body!==undefined?JSON.stringify(o.body):undefined});let j:any;try{j=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(j?.error?.message||'تعذر تنفيذ العملية، حاول مرة أخرى'),{code:j?.error?.code,status:r.status});return j as T}
export const errMsg=(e:any)=>e?.message||'تعذر تنفيذ العملية، حاول مرة أخرى';
