'use client';
import React,{useEffect,useState} from 'react';
import {api,errMsg} from './index';
export function useApi<T>(fn:()=>Promise<T>,deps:any[]=[]){const[data,setData]=useState<T>();const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[refreshing,setRefreshing]=useState(false);const run=async(m='load')=>{m==='load'?setLoading(true):setRefreshing(true);try{setData(await fn());setError('')}catch(e){setError(errMsg(e))}finally{setLoading(false);setRefreshing(false)}};useEffect(()=>{run();},deps);return{data,loading,error,refreshing,reload:()=>run(),refresh:()=>run('refresh'),setData}}
export function Card({children,style}:{children:React.ReactNode;style?:React.CSSProperties}){return <div className="card" style={style}>{children}</div>};
export function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>}
export function State({loading,error,empty,onRetry}:{loading?:boolean;error?:string;empty?:boolean;onRetry?:()=>void}){if(loading)return <div className="loading">جارٍ التحميل...</div>;if(error)return <div className="error">{error}<button className="btn secondary" onClick={onRetry} style={{marginRight:8}}>إعادة المحاولة</button></div>;if(empty)return <div className="empty">لا توجد بيانات</div>;return null}
export function Badge({children,kind=''}:{children:React.ReactNode;kind?:string}){return <span className={`badge ${kind}`}>{children}</span>}
const st=(s:string)=>s==='DELIVERED'?'تم التسليم':s==='CANCELLED'?'ملغي':s==='SEARCHING_DRIVER'?'بحث عن مندوب':s==='FAILED_DELIVERY'?'فشل التسليم':s==='RETURNED'?'مرتجع':s==='DRIVER_ASSIGNED'?'تم التعيين':s==='IN_DELIVERY'?'في الطريق':s;
export function Overview(){const q=useApi(()=>api<any>('/v1/reports/overview'),[]);return <><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<><div className="grid">{[['إجمالي الطلبات',q.data.totalOrders],['تم التسليم',q.data.delivered],['نسبة التسليم',`${q.data.deliveryRate}%`],['الإيرادات',`${(q.data.revenue/100).toLocaleString()} جنيه`],['عمولة مشاوير',`${(q.data.commission/100).toLocaleString()} جنيه`],['متوسط التوصيل',q.data.avgDeliveryMinutes?`${Math.round(q.data.avgDeliveryMinutes)} د`:'-']].map(([l,v])=><Card key={String(l)}><div className="stat"><div className="label">{l}</div><div className="value">{v}</div></div></Card>)}</div><div className="two" style={{marginTop:14}}><Card><h3>أكثر المناطق طلبًا</h3><Table headers={['المنطقة','الطلبات','متوسط السعر']} rows={(q.data.topAreas||[]).map((x:any)=>[x.name||'غير محدد',x.orders,`${Math.round(x.avg_price/100)} جنيه`])}/></Card><Card><h3>أوقات الذروة</h3><Table headers={['الساعة','الطلبات']} rows={(q.data.peakHours||[]).map((x:any)=>[`${x.hour}:00`,x.orders])}/></Card></div></>')}</>}
export function Live(){const q=useApi(()=>api<any>('/v1/admin/live'),[]);useEffect(()=>{const t=setInterval(()=>q.refresh(),10000);return()=>clearInterval(t)},[]);const marker=(x:any)=>{const k=x.marker||'';return <span className={`badge ${k.includes('RED')?'red':k.includes('ORANGE')?'orange':k.includes('BLUE')?'blue':''}`}>{k}</span>};return <><div className="legend"><span><i className="dot" style={{background:'#16a34a'}}/>متاح</span><span><i className="dot" style={{background:'#2563eb'}}/>في طلب</span><span><i className="dot" style={{background:'#f59e0b'}}/>يبحث</span><span><i className="dot" style={{background:'#dc2626'}}/>مشكلة/متأخر</span></div><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<div className="two"><Card><div className="map">{[...(q.data.drivers||[]).map((x:any)=>({...x,kind:x.marker,lat:x.lastLat,lng:x.lastLng})),...(q.data.orders||[]).map((x:any)=>({...x,kind:x.marker,lat:x.stops?.[0]?.lat,lng:x.stops?.[0]?.lng}))].filter((x:any)=>x.lat!=null&&x.lng!=null).map((x:any,i:number)=><span key={i} className="marker" title={x.user?.name||x.code} style={{background:x.kind.includes('GREEN')?'#16a34a':x.kind.includes('BLUE')?'#2563eb':x.kind.includes('ORANGE')?'#f59e0b':'#dc2626',left:`${Math.min(92,Math.max(5,(x.lng-24)/13*100))}%`,top:`${Math.min(92,Math.max(5,(32-x.lat)/11*100))}%`}}/> )}</div></Card><Card><h3>الحالة الحالية</h3><Table headers={['النوع','الرقم','الحالة']} rows={[...(q.data.orders||[]).map((x:any)=>['طلب',x.code,marker(x)]),...(q.data.drivers||[]).map((x:any)=>['مندوب',x.user?.name||x.id,marker(x)])]}/></Card></div>}</>}
export function Orders(){const[qtext,setQ]=useState('');const q=useApi(()=>api<any>('/v1/admin/orders',{query:{q:qtext,limit:50}}),[qtext]);return <><div className="toolbar"><input className="input" placeholder="بحث برقم الطلب/العميل" value={qtext} onChange={e=>setQ(e.target.value)}/><button className="btn secondary" onClick={q.refresh}>تحديث</button></div><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<Table headers={['الطلب','الحالة','العميل','المندوب','الإجمالي','التاريخ']} rows={q.data.items.map((x:any)=>[x.code,<Badge kind={x.status==='CANCELLED'?'red':x.status==='DELIVERED'?'':'blue'}>{st(x.status)}</Badge>,x.customer?.name||x.customer?.phone||'-',x.driver?.user?.name||'لم يعيّن',`${(x.total/100).toLocaleString()} جنيه`,new Date(x.createdAt).toLocaleString('ar-EG')])}/>}</>}
export function Drivers(){const[qtext,setQ]=useState('');const q=useApi(()=>api<any>('/v1/admin/drivers',{query:{q:qtext,limit:50}}),[qtext]);return <><div className="toolbar"><input className="input" placeholder="بحث بالمندوب أو الهاتف" value={qtext} onChange={e=>setQ(e.target.value)}/></div><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<Table headers={['المندوب','الحالة','المركبة','أونلاين','التقييم','الطلبات']} rows={q.data.items.map((x:any)=>[x.user?.name||'-',<Badge kind={x.status==='SUSPENDED'||x.status==='REJECTED'?'red':x.status==='PENDING'?'orange':''}>{x.status}</Badge>,x.vehicles?.[0]?.vehicleType?.nameAr||'-',x.online?'🟢':'⚪',x.rating?.toFixed(1),x.activeOrders])}/>}</>}
export function Customers(){const[qtext,setQ]=useState('');const q=useApi(()=>api<any>('/v1/admin/customers',{query:{q:qtext,limit:50}}),[qtext]);return <><div className="toolbar"><input className="input" placeholder="بحث بالاسم أو الهاتف" value={qtext} onChange={e=>setQ(e.target.value)}/></div><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<Table headers={['العميل','الهاتف','الحالة','الطلبات','منذ']} rows={q.data.items.map((x:any)=>[x.name||'-',x.phone,<Badge kind={x.status==='SUSPENDED'?'red':''}>{x.status}</Badge>,x._count?.orders,new Date(x.createdAt).toLocaleDateString('ar-EG')])}/>}</>}
export function Businesses(){const q=useApi(()=>api<any>('/v1/admin/businesses'),[]);return <><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<Table headers={['الشركة','الحالة','الطلبات','الفروع','المستخدمون']} rows={q.data.items.map((x:any)=>[x.nameAr,x.status,x._count?.orders,x._count?.branches,x._count?.users])}/>}</>}
export function Tickets(){const q=useApi(()=>api<any>('/v1/admin/tickets'),[]);return <><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<Table headers={['الكود','الموضوع','الأولوية','الحالة','أنشئت']} rows={q.data.map((x:any)=>[x.code,x.subject,<Badge kind={x.priority==='URGENT'?'red':'orange'}>{x.priority}</Badge>,x.status,new Date(x.createdAt).toLocaleString('ar-EG')])}/>}</>}
export function Reports(){const q=useApi(()=>api<any>('/v1/reports/overview'),[]);return <><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&<div className="grid"><Card><h3>معدل التسليم</h3><div className="stat"><div className="value">{q.data.deliveryRate}%</div></div></Card><Card><h3>معدل الإلغاء</h3><div className="stat"><div className="value">{q.data.cancelRate}%</div></div></Card><Card><h3>معدل الإرجاع</h3><div className="stat"><div className="value">{q.data.returnRate}%</div></div></Card><Card><h3>متوسط القبول</h3><div className="stat"><div className="value">{q.data.avgAcceptMinutes?Math.round(q.data.avgAcceptMinutes):'-'} د</div></div></Card></div>}</>}
export function Settings(){const q=useApi(()=>api<any>('/v1/admin/settings'),[]);return <><State loading={q.loading} error={q.error} onRetry={q.reload}/>{q.data&&Object.entries(q.data).map(([k,v]:any)=><Card key={k} style={{marginBottom:12}}><h3>{k}</h3><pre style={{whiteSpace:'pre-wrap',direction:'ltr'}}>{JSON.stringify(v,null,2)}</pre></Card>)}</>}
