import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import crypto from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../lib/db.ts';
import { ah, E, AppError } from '../lib/errors.ts';
import { audit } from '../lib/audit.ts';
import { idempotent, idemKey } from '../lib/idempotency.ts';
import { num, paging, pageOut, parseRange } from '../lib/sql.ts';
import { EgPhone, hashSecret } from './auth.ts';
import { invalidateAuthCache } from '../middleware/auth.ts';
import { queues } from '../jobs/queues.ts';
import { createOrder, cancelOrder } from './orders.service.ts';
import { buildQuote } from './pricing.ts';
import { resolvePoint } from './geo.ts';
import { validateBulkRows, BULK_MAX_ROWS } from './bulk.ts';
import { assertSafeWebhookUrl, fanOutWebhook, WEBHOOK_EVENTS } from './webhooks.ts';
import { publicTrackingView } from './tracking.ts';
import { env } from '../config.ts';

export const API_SCOPES = ['orders:create', 'orders:read', 'orders:cancel', 'tracking:read', 'bulk:create'] as const;
const trackingUrl = (t: string) => `${env.PUBLIC_TRACKING_BASE_URL}/${t}`;
const Reason = z.string().trim().min(3).max(300);

type BizRole = 'OWNER' | 'MANAGER' | 'STAFF';
interface BizCtx { businessId: string; role: BizRole; userId: string }
async function bizCtx(req: Request, roles?: BizRole[]): Promise<BizCtx> {
  const id = String(req.headers['x-business-id'] ?? req.user!.businessIds[0] ?? '');
  if (!id || !req.user!.businessIds.includes(id)) throw E.forbidden();
  const m = await prisma.businessUser.findUnique({ where: { businessId_userId: { businessId: id, userId: req.user!.id } }, include: { business: { select: { status: true } } } });
  if (!m) throw E.forbidden();
  if (m.business.status !== 'ACTIVE' && req.method !== 'GET') throw new AppError(403, 'BUSINESS_SUSPENDED', 'حساب الشركة موقوف، تواصل مع الدعم');
  if (roles && !roles.includes(m.role as BizRole)) throw E.forbidden();
  return { businessId: id, role: m.role as BizRole, userId: req.user!.id };
}
const MANAGERS: BizRole[] = ['OWNER', 'MANAGER'];
const Point = z.object({ lat: z.number().min(21).max(32), lng: z.number().min(24).max(37) });
const Drop = Point.extend({ formatted: z.string().trim().min(3).max(300), contactName: z.string().trim().min(2).max(80), contactPhone: EgPhone,
  landmark: z.string().max(200).optional(), instructions: z.string().max(500).optional(), description: z.string().max(300).optional() });
export const BizOrderInput = z.object({
  branchId: z.string().optional(), pickup: Point.extend({ formatted: z.string().max(300).optional(), contactName: z.string().max(80).optional(), contactPhone: EgPhone.optional(), landmark: z.string().max(200).optional() }).optional(),
  dropoff: Drop, vehicleTypeCode: z.string().default('MOTORCYCLE'), packageSizeCode: z.string().default('SMALL'), categoryCode: z.string().default('OTHER'),
  weightKg: z.number().positive().max(3000).default(1), codAmount: z.number().int().min(0).max(100_000_000).default(0), notes: z.string().max(500).optional(), urgent: z.boolean().default(false), scheduledAt: z.coerce.date().nullable().optional(), couponCode: z.string().max(30).nullable().optional(),
}).strict().refine((b) => !!b.branchId || !!b.pickup, { message: 'حدد الفرع أو نقطة الاستلام', path: ['branchId'] }).refine((b) => !b.scheduledAt || b.scheduledAt.getTime() > Date.now() + 10 * 60_000, { message: 'موعد الجدولة يجب أن يكون بعد 10 دقائق على الأقل', path: ['scheduledAt'] });
type BizOrderInput = z.infer<typeof BizOrderInput>;
async function pickupFor(businessId: string, b: BizOrderInput) { if (b.branchId) { const br = await prisma.businessBranch.findFirst({ where: { id: b.branchId, businessId } }); if (!br) throw E.bad('BAD_BRANCH', 'الفرع غير موجود'); return { lat: br.lat, lng: br.lng, formatted: br.address ?? br.name }; } return b.pickup!; }
async function createBizOrder(businessId: string, customerId: string, b: BizOrderInput, actorId: string) { const pickup = await pickupFor(businessId, b); return createOrder({ customerId, businessId, actor: { type: 'BUSINESS', id: actorId }, pickup, dropoffs: [b.dropoff], vehicleTypeCode: b.vehicleTypeCode, packageSizeCode: b.packageSizeCode, categoryCode: b.categoryCode, weightKg: b.weightKg, notes: b.notes, urgent: b.urgent, scheduledAt: b.scheduledAt ?? null, couponCode: b.couponCode ?? null, paymentMethod: 'CASH', codAmount: b.codAmount }); }
const orderOut = (o: { id: string; code: string; status: string; total: number; codAmount: number; trackingToken: string; createdAt: Date }) => ({ id: o.id, code: o.code, status: o.status, total: o.total, codAmount: o.codAmount, createdAt: o.createdAt, trackingUrl: trackingUrl(o.trackingToken) });

export const businessRouter = Router();
businessRouter.get('/profile', ah(async (req, res) => { const c = await bizCtx(req); const b = await prisma.business.findUnique({ where: { id: c.businessId }, include: { branches: true } }); res.json({ ...b, myRole: c.role }); }));
businessRouter.get('/summary', ah(async (req, res) => { const c = await bizCtx(req); const { from, to } = parseRange(req.query, 30); const [k] = await prisma.$queryRaw<any[]>`SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status='DELIVERED') AS delivered, COUNT(*) FILTER (WHERE status='CANCELLED') AS cancelled, COUNT(*) FILTER (WHERE status IN ('FAILED_DELIVERY','RETURNING','RETURNED')) AS failed_or_returned, COUNT(*) FILTER (WHERE status NOT IN ('DELIVERED','CANCELLED','RETURNED')) AS open, COALESCE(SUM(total) FILTER (WHERE status='DELIVERED'),0)::bigint AS fees, COALESCE(SUM("codAmount") FILTER (WHERE status='DELIVERED'),0)::bigint AS cod_collected, COALESCE(SUM("codAmount") FILTER (WHERE status NOT IN ('DELIVERED','CANCELLED','RETURNED')),0)::bigint AS cod_pending, AVG(EXTRACT(EPOCH FROM ("deliveredAt"-"createdAt"))/60) FILTER (WHERE status='DELIVERED')::float AS avg_delivery_min FROM "Order" WHERE "businessId" = ${c.businessId} AND "createdAt" BETWEEN ${from} AND ${to}`; const series = await prisma.$queryRaw<any[]>`SELECT to_char(date_trunc('day', "createdAt" AT TIME ZONE 'Africa/Cairo'),'YYYY-MM-DD') AS day, COUNT(*) AS orders, COUNT(*) FILTER (WHERE status='DELIVERED') AS delivered, COALESCE(SUM("codAmount") FILTER (WHERE status='DELIVERED'),0)::bigint AS cod FROM "Order" WHERE "businessId" = ${c.businessId} AND "createdAt" BETWEEN ${from} AND ${to} GROUP BY 1 ORDER BY 1`; const areas = await prisma.$queryRaw<any[]>`SELECT g."nameAr" AS name, COUNT(*) AS orders, COUNT(*) FILTER (WHERE o.status='DELIVERED') AS delivered FROM "Order" o JOIN "OrderStop" s ON s."orderId"=o.id AND s.type='DROPOFF' LEFT JOIN "GeoUnit" g ON g.id=s."geoUnitId" WHERE o."businessId" = ${c.businessId} AND o."createdAt" BETWEEN ${from} AND ${to} GROUP BY 1 ORDER BY 2 DESC LIMIT 10`; res.json({ range: { from, to }, kpis: num(k), series: series.map(num), topAreas: areas.map(num) }); }));

businessRouter.get('/orders', ah(async (req, res) => { const c = await bizCtx(req); const q = req.query as Record<string, string | undefined>; const p = paging(q); const range = q.from || q.to ? parseRange(q) : null; const where: Prisma.OrderWhereInput = { businessId: c.businessId, ...(q.status ? { status: { in: q.status.split(',') as any } } : {}), ...(range ? { createdAt: { gte: range.from, lte: range.to } } : {}), ...(q.cod === '1' ? { codAmount: { gt: 0 } } : {}), ...(q.q ? { OR: [{ code: { contains: q.q.trim(), mode: 'insensitive' } }, { stops: { some: { type: 'DROPOFF', OR: [{ contactPhone: { contains: q.q.trim() } }, { contactName: { contains: q.q.trim(), mode: 'insensitive' } }] } } }] } : {}) }; const [items, total] = await Promise.all([prisma.order.findMany({ where, orderBy: { createdAt: 'desc' }, take: p.take, skip: p.skip, select: { id: true, code: true, status: true, total: true, codAmount: true, createdAt: true, deliveredAt: true, trackingToken: true, stops: { where: { type: 'DROPOFF' }, select: { contactName: true, contactPhone: true, formatted: true } } } }), prisma.order.count({ where })]); res.json(pageOut(items.map(({ trackingToken, ...o }) => ({ ...o, trackingUrl: trackingUrl(trackingToken) })), total, p)); }));
businessRouter.get('/orders/:id', ah(async (req, res) => { const c = await bizCtx(req); const o = await prisma.order.findFirst({ where: { id: req.params.id, businessId: c.businessId }, include: { stops: { orderBy: { seq: 'asc' } }, history: { orderBy: { at: 'asc' }, select: { toStatus: true, at: true, reason: true } }, proofs: { select: { kind: true, photoUrl: true, recipientName: true, otpVerified: true, capturedAt: true } }, payments: { select: { method: true, amount: true, status: true } }, driver: { select: { lastLat: true, lastLng: true, lastLocationAt: true, user: { select: { name: true, phone: true } } } } } }); if (!o) throw E.notFound('الطلب'); const { deliveryOtpHash, trackingToken, ...safe } = o; res.json({ ...safe, trackingUrl: trackingUrl(trackingToken) }); }));
businessRouter.post('/quote', ah(async (req, res) => { const c = await bizCtx(req); const b = BizOrderInput.parse(req.body); const pickup = await pickupFor(c.businessId, b); const q = await buildQuote({ pickup, dropoffs: [b.dropoff], vehicleTypeCode: b.vehicleTypeCode, packageSizeCode: b.packageSizeCode, weightKg: b.weightKg, urgent: b.urgent, scheduledAt: b.scheduledAt ?? null, couponCode: b.couponCode ?? null, userId: c.userId, businessId: c.businessId }); res.json({ total: q.total, subtotal: q.subtotal, discount: q.discount, distanceKm: q.distanceKm, durationMin: q.durationMin, lines: q.lines, pickupArea: q.pickupGeo.label, dropoffArea: q.dropGeos[0].label }); }));
businessRouter.post('/orders', ah(async (req, res) => { const c = await bizCtx(req); const b = BizOrderInput.parse(req.body); const r = await idempotent(`business:${c.businessId}`, idemKey(req), async () => { const { order } = await createBizOrder(c.businessId, c.userId, b, c.userId); await audit(prisma, { actorId: c.userId, action: 'business.order.create', entityType: 'Order', entityId: order.id, after: { businessId: c.businessId, code: order.code }, ip: req.ip }); return { status: 201, body: orderOut(order) }; }); res.status(r.status).json(r.body); }));
businessRouter.post('/orders/:id/cancel', ah(async (req, res) => { const c = await bizCtx(req); const { reason } = z.object({ reason: Reason }).parse(req.body); const o = await prisma.order.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!o) throw E.notFound('الطلب'); await cancelOrder(o.id, { type: 'BUSINESS', id: c.userId }, reason); await audit(prisma, { actorId: c.userId, action: 'business.order.cancel', entityType: 'Order', entityId: o.id, before: { status: o.status }, after: { reason }, ip: req.ip }); res.json({ ok: true }); }));

const BulkBody = z.object({ rows: z.array(z.record(z.any())).min(1, 'الملف فارغ').max(BULK_MAX_ROWS, `الحد الأقصى ${BULK_MAX_ROWS} صف`), fileName: z.string().max(200).default('upload') });
businessRouter.post('/bulk/validate', ah(async (req, res) => { const c = await bizCtx(req); const { rows } = BulkBody.parse(req.body); const checked = await validateBulkRows(c.businessId, rows); res.json({ total: checked.length, ok: checked.filter((r) => r.ok).length, failed: checked.filter((r) => !r.ok).length, rows: checked.map(({ data, ...r }) => ({ ...r, preview: data ? { recipientName: data.recipientName, recipientPhone: data.recipientPhone, address: data.address, codAmountEgp: data.codAmountEgp } : undefined })) }); }));
businessRouter.post('/bulk', ah(async (req, res) => { const c = await bizCtx(req); const { rows, fileName } = BulkBody.parse(req.body); const r = await idempotent(`bulk:${c.businessId}`, idemKey(req), async () => { const up = await prisma.bulkUpload.create({ data: { businessId: c.businessId, createdById: c.userId, fileUrl: fileName, status: 'QUEUED', totalRows: rows.length } }); await queues.bulk.add('bulk', { uploadId: up.id, rows, userId: c.userId, businessId: c.businessId }, { jobId: `bulk:${up.id}` }); await audit(prisma, { actorId: c.userId, action: 'business.bulk.create', entityType: 'BulkUpload', entityId: up.id, after: { rows: rows.length, fileName }, ip: req.ip }); return { status: 202, body: { uploadId: up.id, messageAr: 'جارٍ معالجة الملف' } }; }); res.status(r.status).json(r.body); }));
businessRouter.get('/bulk', ah(async (req, res) => { const c = await bizCtx(req); const p = paging(req.query); const where = { businessId: c.businessId }; const [items, total] = await Promise.all([prisma.bulkUpload.findMany({ where, orderBy: { createdAt: 'desc' }, take: p.take, skip: p.skip, select: { id: true, fileUrl: true, status: true, totalRows: true, okRows: true, createdAt: true, finishedAt: true } }), prisma.bulkUpload.count({ where })]); res.json(pageOut(items, total, p)); }));
businessRouter.get('/bulk/:id', ah(async (req, res) => { const c = await bizCtx(req); const up = await prisma.bulkUpload.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!up) throw E.notFound('الملف'); res.json(up); }));

businessRouter.get('/statement', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const q = req.query as Record<string, string | undefined>; const p = paging(q, 200); const w = await prisma.wallet.findUnique({ where: { ownerType_ownerId: { ownerType: 'BUSINESS', ownerId: c.businessId } } }); const range = q.from || q.to ? parseRange(q) : null; const where: Prisma.WalletTransactionWhereInput = { walletId: w?.id ?? '__none__', ...(q.type ? { type: q.type } : {}), ...(range ? { createdAt: { gte: range.from, lte: range.to } } : {}) }; const [items, total, codPending, byType] = await Promise.all([prisma.walletTransaction.findMany({ where, orderBy: { createdAt: 'desc' }, take: p.take, skip: p.skip }), prisma.walletTransaction.count({ where }), prisma.order.aggregate({ where: { businessId: c.businessId, status: { notIn: ['DELIVERED', 'CANCELLED', 'RETURNED'] } }, _sum: { codAmount: true } }), prisma.walletTransaction.groupBy({ by: ['type'], where, _sum: { amount: true } })]); const orders = await prisma.order.findMany({ where: { id: { in: items.map((t) => t.orderId).filter(Boolean) as string[] }, businessId: c.businessId }, select: { id: true, code: true } }); res.json({ balance: w?.balance ?? 0, codPending: codPending._sum.codAmount ?? 0, totals: Object.fromEntries(byType.map((t) => [t.type, t._sum.amount ?? 0])), ...pageOut(items.map((t) => ({ ...t, orderCode: orders.find((o) => o.id === t.orderId)?.code ?? null })), total, p) }); }));

const BranchInput = z.object({ name: z.string().trim().min(2).max(80), lat: z.number().min(21).max(32), lng: z.number().min(24).max(37), address: z.string().max(300).optional() });
businessRouter.get('/branches', ah(async (req, res) => { const c = await bizCtx(req); res.json(await prisma.businessBranch.findMany({ where: { businessId: c.businessId } })); }));
businessRouter.post('/branches', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = BranchInput.parse(req.body); const g = await resolvePoint(b); if (!g) throw E.bad('AREA_NOT_SERVED', 'موقع الفرع خارج نطاق الخدمة حاليًا'); const row = await prisma.businessBranch.create({ data: { ...b, businessId: c.businessId, geoUnitId: g.unit.id } }); await audit(prisma, { actorId: c.userId, action: 'business.branch.create', entityType: 'Business', entityId: c.businessId, after: row, ip: req.ip }); res.status(201).json(row); }));
businessRouter.patch('/branches/:id', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = BranchInput.partial().parse(req.body); const before = await prisma.businessBranch.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!before) throw E.notFound('الفرع'); let geoUnitId = before.geoUnitId; if (b.lat != null || b.lng != null) { const g = await resolvePoint({ lat: b.lat ?? before.lat, lng: b.lng ?? before.lng }); if (!g) throw E.bad('AREA_NOT_SERVED', 'موقع الفرع خارج نطاق الخدمة حاليًا'); geoUnitId = g.unit.id; } const row = await prisma.businessBranch.update({ where: { id: before.id }, data: { ...b, geoUnitId } }); await audit(prisma, { actorId: c.userId, action: 'business.branch.update', entityType: 'Business', entityId: c.businessId, before, after: row, ip: req.ip }); res.json(row); }));
businessRouter.delete('/branches/:id', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const before = await prisma.businessBranch.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!before) throw E.notFound('الفرع'); if ((await prisma.businessBranch.count({ where: { businessId: c.businessId } })) <= 1) throw E.bad('LAST_BRANCH', 'لا يمكن حذف آخر فرع'); await prisma.businessBranch.delete({ where: { id: before.id } }); await audit(prisma, { actorId: c.userId, action: 'business.branch.delete', entityType: 'Business', entityId: c.businessId, before, ip: req.ip }); res.json({ ok: true }); }));

businessRouter.get('/staff', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const rows = await prisma.businessUser.findMany({ where: { businessId: c.businessId }, include: { user: { select: { id: true, name: true, phone: true, status: true } } } }); res.json(rows.map((r) => ({ userId: r.userId, role: r.role, ...r.user }))); }));
const canGrant = (me: BizRole, role: BizRole) => role !== 'OWNER' && (me === 'OWNER' || role === 'STAFF');
businessRouter.post('/staff', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = z.object({ phone: EgPhone, name: z.string().trim().min(2).max(80).optional(), role: z.enum(['MANAGER', 'STAFF']) }).parse(req.body); if (!canGrant(c.role, b.role)) throw E.forbidden(); let u = await prisma.user.findUnique({ where: { phone: b.phone } }); if (!u) u = await prisma.user.create({ data: { phone: b.phone, name: b.name, referralCode: 'B' + crypto.randomBytes(4).toString('hex').toUpperCase() } }); const existing = await prisma.businessUser.findUnique({ where: { businessId_userId: { businessId: c.businessId, userId: u.id } } }); if (existing) throw E.conflict('ALREADY_MEMBER', 'المستخدم عضو بالفعل'); await prisma.businessUser.create({ data: { businessId: c.businessId, userId: u.id, role: b.role } }); for (const code of ['BUSINESS', 'CUSTOMER']) { const role = await prisma.role.findUnique({ where: { code } }); if (role) await prisma.userRole.upsert({ where: { userId_roleId: { userId: u.id, roleId: role.id } }, update: {}, create: { userId: u.id, roleId: role.id } }); } invalidateAuthCache(u.id); await audit(prisma, { actorId: c.userId, action: 'business.staff.add', entityType: 'Business', entityId: c.businessId, after: { userId: u.id, role: b.role }, ip: req.ip }); res.status(201).json({ ok: true, userId: u.id }); }));
businessRouter.patch('/staff/:userId', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const { role } = z.object({ role: z.enum(['MANAGER', 'STAFF']) }).parse(req.body); const m = await prisma.businessUser.findUnique({ where: { businessId_userId: { businessId: c.businessId, userId: req.params.userId } } }); if (!m) throw E.notFound('الموظف'); if (m.role === 'OWNER' || m.userId === c.userId || !canGrant(c.role, role) || !canGrant(c.role, m.role as BizRole)) throw E.forbidden(); await prisma.businessUser.update({ where: { businessId_userId: { businessId: c.businessId, userId: m.userId } }, data: { role } }); await audit(prisma, { actorId: c.userId, action: 'business.staff.role', entityType: 'Business', entityId: c.businessId, before: { role: m.role }, after: { userId: m.userId, role }, ip: req.ip }); res.json({ ok: true }); }));
businessRouter.delete('/staff/:userId', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const m = await prisma.businessUser.findUnique({ where: { businessId_userId: { businessId: c.businessId, userId: req.params.userId } } }); if (!m) throw E.notFound('الموظف'); if (m.role === 'OWNER' || m.userId === c.userId || !canGrant(c.role, m.role as BizRole)) throw E.forbidden(); await prisma.businessUser.delete({ where: { businessId_userId: { businessId: c.businessId, userId: m.userId } } }); invalidateAuthCache(m.userId); await audit(prisma, { actorId: c.userId, action: 'business.staff.remove', entityType: 'Business', entityId: c.businessId, before: { userId: m.userId, role: m.role }, ip: req.ip }); res.json({ ok: true }); }));

const newKey = () => ({ prefix: 'msh_' + crypto.randomBytes(6).toString('hex'), secret: crypto.randomBytes(32).toString('base64url') });
const keyOut = (k: any) => ({ id: k.id, name: k.name, prefix: k.prefix, scopes: k.scopes, rateLimitPerMin: k.rateLimitPerMin, revokedAt: k.revokedAt, lastUsedAt: k.lastUsedAt, createdAt: k.createdAt, rotatedFromId: k.rotatedFromId });
businessRouter.get('/api-keys', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); res.json((await prisma.apiKey.findMany({ where: { businessId: c.businessId }, orderBy: { createdAt: 'desc' } })).map(keyOut)); }));
businessRouter.post('/api-keys', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = z.object({ name: z.string().trim().min(2).max(60), scopes: z.array(z.enum(API_SCOPES)).min(1), rateLimitPerMin: z.number().int().min(1).max(600).default(60) }).parse(req.body); if ((await prisma.apiKey.count({ where: { businessId: c.businessId, revokedAt: null } })) >= 10) throw E.bad('TOO_MANY_KEYS', 'الحد الأقصى 10 مفاتيح فعّالة'); const { prefix, secret } = newKey(); const k = await prisma.apiKey.create({ data: { businessId: c.businessId, name: b.name, prefix, keyHash: hashSecret(secret), scopes: [...new Set(b.scopes)], rateLimitPerMin: b.rateLimitPerMin } }); await audit(prisma, { actorId: c.userId, action: 'apikey.create', entityType: 'Business', entityId: c.businessId, after: { prefix, scopes: b.scopes }, ip: req.ip }); res.status(201).json({ ...keyOut(k), apiKey: `${prefix}.${secret}`, noteAr: 'احفظ المفتاح الآن، لن يظهر مرة أخرى' }); }));
businessRouter.post('/api-keys/:id/rotate', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const old = await prisma.apiKey.findFirst({ where: { id: req.params.id, businessId: c.businessId, revokedAt: null } }); if (!old) throw E.notFound('المفتاح'); const { prefix, secret } = newKey(); const k = await prisma.$transaction(async (tx) => { const k = await tx.apiKey.create({ data: { businessId: c.businessId, name: old.name, prefix, keyHash: hashSecret(secret), scopes: old.scopes, rateLimitPerMin: old.rateLimitPerMin, rotatedFromId: old.id } }); await tx.apiKey.update({ where: { id: old.id }, data: { revokedAt: new Date() } }); return k; }); await audit(prisma, { actorId: c.userId, action: 'apikey.rotate', entityType: 'Business', entityId: c.businessId, before: { prefix: old.prefix }, after: { prefix }, ip: req.ip }); res.status(201).json({ ...keyOut(k), apiKey: `${prefix}.${secret}`, noteAr: 'تم إيقاف المفتاح القديم فورًا. احفظ المفتاح الجديد الآن' }); }));
businessRouter.post('/api-keys/:id/revoke', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const k = await prisma.apiKey.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!k) throw E.notFound('المفتاح'); if (!k.revokedAt) await prisma.apiKey.update({ where: { id: k.id }, data: { revokedAt: new Date() } }); await audit(prisma, { actorId: c.userId, action: 'apikey.revoke', entityType: 'Business', entityId: c.businessId, after: { prefix: k.prefix }, ip: req.ip }); res.json({ ok: true }); }));
businessRouter.get('/api-keys/:id/usage', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const p = paging(req.query, 200); const k = await prisma.apiKey.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!k) throw E.notFound('المفتاح'); const since = new Date(Date.now() - 14 * 86400_000); const [items, total, daily] = await Promise.all([prisma.apiUsageLog.findMany({ where: { apiKeyId: k.id }, orderBy: { at: 'desc' }, take: p.take, skip: p.skip }), prisma.apiUsageLog.count({ where: { apiKeyId: k.id } }), prisma.$queryRaw<any[]>`SELECT to_char(date_trunc('day', at AT TIME ZONE 'Africa/Cairo'),'YYYY-MM-DD') AS day, COUNT(*) AS requests, COUNT(*) FILTER (WHERE status >= 400) AS errors, AVG(ms)::int AS avg_ms FROM "ApiUsageLog" WHERE "apiKeyId" = ${k.id} AND at >= ${since} GROUP BY 1 ORDER BY 1`]); res.json({ ...pageOut(items.map((i) => ({ ...i, id: i.id.toString() })), total, p), daily: daily.map(num) }); }));

const hookOut = (w: any) => ({ id: w.id, url: w.url, events: w.events, active: w.active, createdAt: w.createdAt }); const Events = z.array(z.enum(WEBHOOK_EVENTS as [string, ...string[]])).min(1);
businessRouter.get('/webhooks', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); res.json({ events: WEBHOOK_EVENTS, items: (await prisma.webhook.findMany({ where: { businessId: c.businessId }, orderBy: { createdAt: 'desc' } })).map(hookOut) }); }));
businessRouter.post('/webhooks', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = z.object({ url: z.string().url(), events: Events }).parse(req.body); const url = assertSafeWebhookUrl(b.url); if ((await prisma.webhook.count({ where: { businessId: c.businessId } })) >= 10) throw E.bad('TOO_MANY_WEBHOOKS', 'الحد الأقصى 10 روابط'); const secret = crypto.randomBytes(32).toString('hex'); const w = await prisma.webhook.create({ data: { businessId: c.businessId, url, events: [...new Set(b.events)], secret } }); await audit(prisma, { actorId: c.userId, action: 'webhook.create', entityType: 'Business', entityId: c.businessId, after: { url, events: b.events }, ip: req.ip }); res.status(201).json({ ...hookOut(w), signingSecret: secret, noteAr: 'احفظ مفتاح التوقيع الآن، لن يظهر مرة أخرى' }); }));
businessRouter.patch('/webhooks/:id', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const b = z.object({ url: z.string().url().optional(), events: Events.optional(), active: z.boolean().optional() }).parse(req.body); const w = await prisma.webhook.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!w) throw E.notFound('الرابط'); const row = await prisma.webhook.update({ where: { id: w.id }, data: { ...b, ...(b.url ? { url: assertSafeWebhookUrl(b.url) } : {}) } }); await audit(prisma, { actorId: c.userId, action: 'webhook.update', entityType: 'Business', entityId: c.businessId, before: hookOut(w), after: hookOut(row), ip: req.ip }); res.json(hookOut(row)); }));
businessRouter.delete('/webhooks/:id', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const w = await prisma.webhook.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!w) throw E.notFound('الرابط'); await prisma.webhook.delete({ where: { id: w.id } }); await audit(prisma, { actorId: c.userId, action: 'webhook.delete', entityType: 'Business', entityId: c.businessId, before: hookOut(w), ip: req.ip }); res.json({ ok: true }); }));
businessRouter.post('/webhooks/:id/test', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const w = await prisma.webhook.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!w) throw E.notFound('الرابط'); if (!w.active) throw E.bad('INACTIVE', 'فعّل الرابط أولًا'); await fanOutWebhook(c.businessId, 'test.ping', undefined, w.id); res.status(202).json({ ok: true, messageAr: 'تم إرسال حدث تجريبي، راجع سجل الإرسال' }); }));
businessRouter.get('/webhooks/:id/deliveries', ah(async (req, res) => { const c = await bizCtx(req, MANAGERS); const p = paging(req.query); const w = await prisma.webhook.findFirst({ where: { id: req.params.id, businessId: c.businessId } }); if (!w) throw E.notFound('الرابط'); const [items, total] = await Promise.all([prisma.webhookDelivery.findMany({ where: { webhookId: w.id }, orderBy: { createdAt: 'desc' }, take: p.take, skip: p.skip }), prisma.webhookDelivery.count({ where: { webhookId: w.id } })]); res.json(pageOut(items, total, p)); }));

export const businessApiRouter = Router();
type ApiReq = Request & { apiKey?: { id: string; businessId: string; prefix: string; scopes: string[]; rateLimitPerMin: number } };
async function apiKeyAuth(req: ApiReq, _res: Response, next: NextFunction) { try { const h = String(req.headers['x-api-key'] ?? (req.headers.authorization?.startsWith('Bearer msh_') ? req.headers.authorization.slice(7) : '')); const [prefix, secret] = h.split('.'); const k = prefix && secret ? await prisma.apiKey.findUnique({ where: { prefix }, include: { business: { select: { status: true } } } }) : null; const ok = !!k && crypto.timingSafeEqual(Buffer.from(hashSecret(secret ?? '')), Buffer.from(k.keyHash)); if (!k || !ok || k.revokedAt) throw new AppError(401, 'INVALID_API_KEY', 'مفتاح API غير صالح أو ملغي'); if (k.business.status !== 'ACTIVE') throw new AppError(403, 'BUSINESS_SUSPENDED', 'حساب الشركة موقوف'); req.apiKey = k; next(); } catch (e) { next(e); } }
function usageLog(req: ApiReq, res: Response, next: NextFunction) { const t = Date.now(); res.on('finish', () => { if (!req.apiKey) return; prisma.apiUsageLog.create({ data: { apiKeyId: req.apiKey.id, method: req.method, path: (req.route?.path ? `${req.baseUrl}${req.route.path}` : req.originalUrl.split('?')[0]).slice(0, 200), status: res.statusCode, ms: Date.now() - t, ip: req.ip } }).catch(() => {}); prisma.apiKey.update({ where: { id: req.apiKey.id }, data: { lastUsedAt: new Date() } }).catch(() => {}); }); next(); }
 businessApiRouter.use(apiKeyAuth as any); businessApiRouter.use(usageLog as any); businessApiRouter.use(rateLimit({ windowMs: 60_000, limit: (req: any) => req.apiKey?.rateLimitPerMin ?? 60, keyGenerator: (req: any) => req.apiKey?.prefix ?? req.ip, standardHeaders: true, handler: (_req, res) => res.status(429).json({ error: { code: 'RATE_LIMITED', message: 'تم تجاوز حد الطلبات، حاول بعد دقيقة' } }) }));
const scope = (s: (typeof API_SCOPES)[number]) => (req: ApiReq, _res: Response, next: NextFunction) => (req.apiKey!.scopes.includes(s) ? next() : next(new AppError(403, 'SCOPE_REQUIRED', `المفتاح لا يملك صلاحية ${s}`)));
async function apiOwner(businessId: string) { const owner = await prisma.businessUser.findFirst({ where: { businessId, role: 'OWNER' } }); if (!owner) throw E.bad('NO_OWNER', 'لا يوجد مالك للحساب'); return owner.userId; }
async function apiOrder(req: ApiReq) { const ref = String(req.params.id); const o = await prisma.order.findFirst({ where: { businessId: req.apiKey!.businessId, OR: [{ id: ref }, { code: ref }] } }); if (!o) throw E.notFound('الطلب'); return o; }
businessApiRouter.get('/me', ah(async (req: ApiReq, res) => res.json({ businessId: req.apiKey!.businessId, scopes: req.apiKey!.scopes, rateLimitPerMin: req.apiKey!.rateLimitPerMin })));
businessApiRouter.post('/orders', scope('orders:create'), ah(async (req: ApiReq, res) => { const b = BizOrderInput.parse(req.body); const businessId = req.apiKey!.businessId; const r = await idempotent(`api:${businessId}`, idemKey(req), async () => { const { order } = await createBizOrder(businessId, await apiOwner(businessId), b, `apikey:${req.apiKey!.prefix}`); await audit(prisma, { actorId: undefined, action: 'api.order.create', entityType: 'Order', entityId: order.id, after: { businessId, apiKey: req.apiKey!.prefix, code: order.code }, ip: req.ip }); return { status: 201, body: orderOut(order) }; }); res.setHeader('Idempotent-Replayed', String(r.replayed)).status(r.status).json(r.body); }));
businessApiRouter.get('/orders/:id', scope('orders:read'), ah(async (req: ApiReq, res) => { const o = await apiOrder(req); const stops = await prisma.orderStop.findMany({ where: { orderId: o.id }, orderBy: { seq: 'asc' }, select: { type: true, formatted: true, contactName: true, completedAt: true } }); const history = await prisma.orderStatusHistory.findMany({ where: { orderId: o.id }, orderBy: { at: 'asc' }, select: { toStatus: true, at: true } }); res.json({ ...orderOut(o), deliveredAt: o.deliveredAt, failReason: o.failReason, cancelReason: o.cancelReason, stops, history }); }));
businessApiRouter.get('/orders/:id/tracking', scope('tracking:read'), ah(async (req: ApiReq, res) => { const o = await apiOrder(req); res.json({ ...(await publicTrackingView({ id: o.id })), trackingUrl: trackingUrl(o.trackingToken) }); }));
businessApiRouter.post('/orders/:id/cancel', scope('orders:cancel'), ah(async (req: ApiReq, res) => { const { reason } = z.object({ reason: Reason.default('cancelled via API') }).parse(req.body ?? {}); const o = await apiOrder(req); await cancelOrder(o.id, { type: 'BUSINESS', id: `apikey:${req.apiKey!.prefix}` }, reason); await audit(prisma, { actorId: undefined, action: 'api.order.cancel', entityType: 'Order', entityId: o.id, after: { apiKey: req.apiKey!.prefix, reason }, ip: req.ip }); res.json({ ok: true }); }));
businessApiRouter.post('/bulk', scope('bulk:create'), ah(async (req: ApiReq, res) => { const { rows, fileName } = BulkBody.parse(req.body); const businessId = req.apiKey!.businessId; const r = await idempotent(`api-bulk:${businessId}`, idemKey(req), async () => { const owner = await apiOwner(businessId); const up = await prisma.bulkUpload.create({ data: { businessId, createdById: owner, fileUrl: `api:${fileName}`, status: 'QUEUED', totalRows: rows.length } }); await queues.bulk.add('bulk', { uploadId: up.id, rows, userId: owner, businessId }, { jobId: `bulk:${up.id}` }); return { status: 202, body: { uploadId: up.id } }; }); res.status(r.status).json(r.body); }));
businessApiRouter.get('/bulk/:id', scope('bulk:create'), ah(async (req: ApiReq, res) => { const up = await prisma.bulkUpload.findFirst({ where: { id: req.params.id, businessId: req.apiKey!.businessId }, select: { id: true, status: true, totalRows: true, okRows: true, errors: true, createdAt: true, finishedAt: true } }); if (!up) throw E.notFound('الملف'); res.json(up); }));
